

var bodyParser = require('body-parser');
const express = require('express');
const app = express();
const port = 3000;

const mariadb = require('mariadb');
const pool = mariadb.createPool({
        host : 'localhost',
        user : 'root',
        password: 'root',
        port: 3306,
        connectionLimit:5
});

const swaggerJsdoc = require('swagger-jsdoc');
const swaggerUi = require('swagger-ui-express');
const cors = require('cors');

const options = {
    swaggerDefinition :{
        info:{
            title: 'Pallavi ITIS-Week05',
            version: '1.0.0',
            description: 'API autogenerated by'
        },
        host: '137.184.100.105:3000',
        basePath: '/',
    },
    apis: ['./server.js'],
}

const specs = swaggerJsdoc(options);

app.use('/docs', swaggerUi.serve, swaggerUi.setup(specs));
app.use(cors());

app.use(bodyParser.urlencoded({ extended: true }));
app.use(bodyParser.json());

/**
 * @swagger
 * /agents:
 *     get:
 *       description: Return agents
 *       produces:
 *          - application/json
 *       responses:
 *          200:
 *              description: Object agents details
*/
app.listen(port, ()=>{
    console.log(`API server at ${port}`);

app.get('/agents',(request,response) =>{
    pool.query('SELECT * from sample.agents')
        .then(res => {
                response.statusCode = 200;
                response.setHeader('Content-Type','Application/json');
                response.send(res);
                })
        .catch(err =>{ 
                response.statusCode = 404;
                console.error('Error exccuting query', err.stack);
                response.setHeader('Content-Type','text/plain');
                response.send('Error executing query' + err.stack);
        });
    // res.json(prices);
});


/**
 * @swagger
 * /agents:
 *  put:
 *    description: Updates agents
 *    consumes: 
 *    - application/json
 *    produces:
 *    - application/json
 *    parameters:
 *    - in: body
 *      name: agentCode
 *      required: true
 *      schema:
 *        type: string
 *        $ref: "#/definitions/agentPut"
 *    requestBody:
 *      request: true
 *      content:
 *        application/json:
 *          schema:
 *            $ref: "#definitions/agentPut"
 *    responses: 
 *      200:
 *       description: A successfull response from agents 
 * definitions:
 *   agentPut:
 *     type: object
 *     required:
 *     - agentCode
 *     - agentName
 *     - workingArea
 *     - commission
 *     - phoneNo
 *     - country
 *     properties:
 *       agentCode:
 *         type: string
 *         example: A485
 *       agentName:
 *         type: string
 *         example: PallaviBhadri
 *       workingArea: 
 *         type: string
 *         example: Pune
 *       commission:
 *         type: number
 *         example: 5
 *       phoneNo:
 *         type: string
 *         example: 4147377529
 *       country:
 *         type: string
 *         example: India
*/
app.put('/agents', (request,response) =>{
    pool.query(`update sample.agents set agent_name = '${request['body'].agentName}',  working_area = '${request['body'].workingArea}', commission  = '${request['body'].commission}', phone_no = '${request['body'].phoneNo}', country = '${request['body'].country}' where agent_code = '${request['body'].agentCode}'`).then(res => {
                console.log(res.affectedRows);
                if(res.affectedRows > 0)
                {
                        response.statusCode = 200;
                        response.setHeader('Content-Type','Application/json');
                        response.send(res);
                }
                else{
                        response.statusCode = 201;
                        response.setHeader('Content-Type','text/plain');
                        response.send("The agent is not located in the table - Operation  unsuccessful");
                }
              })
        .catch(err =>{
                response.statusCode = 404;
                console.error('Error exccuting query', err.stack);
                response.setHeader('Content-Type','text/plain');
                response.send('Error executing query' + err.stack);
        });
});



/**
 * @swagger
 * /agents:
 *  post:
 *    description: Updates agents
 *    consumes:
 *    - application/json
 *    produces:
 *    - application/json
 *    parameters:
 *    - in: body
 *      name: agentCode
 *      required: true
 *      schema:
 *        type: string
 *        $ref: "#/definitions/agentPost"
 *    requestBody:
 *      request: true
 *      content:
 *        application/json:
 *          schema:
 *            $ref: "#definitions/agentPost"
 *    responses:
 *      200:
 *       description: A successfull response from agents
 * definitions:
 *   agentPost:
 *     type: object
 *     required:
 *     - agentCode
 *     - agentName
 *     - workingArea
 *     - commission
 *     - phoneNo
 *     - country
 *     properties:
 *       agentCode:
 *         type: string
 *         example: A007
 *       agentName:
 *         type: string
 *         example: PallaviBhadri
 *       workingArea:
 *         type: string
 *         example: Pune
 *       commission:
 *         type: number
 *         example: 10
 *       phoneNo:
 *         type: string
 *         example: 4147377529
 *       country:
 *         type: string
 *         example: India
*/
app.post('/agents',(request,response) =>{
    pool.query(`insert into sample.agents values ('${request['body'].agentCode}', '${request['body'].agentName}', '${request['body'].workingArea}', '${request['body'].commission}', '${request['body'].phone_no}', '${request['body'].country}')`).then(res => {
               console.log(res);
                 if(res.affectedRows > 0){
                        response.statusCode = 200;
                        response.setHeader('Content-Type','Application/json');
                        response.send(res);
                }else{
                        response.statusCode = 201;
                        response.setHeader('Content-Type','text/plain');
                        response.send('No rows added -Operation unsuccessful');
                }
               })
        .catch(err =>{
                response.statusCode = 500;
                console.error('Error exccuting query', err.stack);
                response.setHeader('Content-Type','text/plain');
                response.send('Error executing query' + err.stack);
        });
});

/**
 * @swagger
 * /agents:
 *  delete:
 *    description: Remove products from agents
 *    consumes: 
 *    - application/json
 *    produces:
 *    - application/json
 *    parameters:
 *    - in: body
 *      name: name
 *      required: true
 *      schema:
 *        type: string
 *        $ref: "#/definitions/agentDel"
 *    responses: 
 *      200:
 *       description: A successfull response from agents
 * definitions:
 *   agentDel:
 *     type: object
 *     required:
 *     - agentCode
 *     properties:
 *       agentCode:
 *         type: string
 *         example: 'A145'
*/
app.delete('/agents',(request,response) =>{
    pool.query(`delete from sample.agents where agent_Code =  ('${request['body'].agentCode}')`).then(res => {
               console.log(res);
                 if(res.affectedRows > 0){
                        response.statusCode = 200;
                        response.setHeader('Content-Type','Application/json');
                        response.send(res);
                }else{
                        response.statusCode = 201;
                        response.setHeader('Content-Type','text/plain');
                        response.send('No rows delete - operation unsuccessful');
                }
               })
        .catch(err =>{
                response.statusCode = 500;
                console.error('Error exccuting query', err.stack);
                response.setHeader('Content-Type','text/plain');
                response.send('Error executing query' + err.stack);
        });
});

/**
 * @swagger
 * /agents:
 *  patch:
 *    description: updates or inserts agents
 *    consumes:
 *    - application/json
 *    produces:
 *    - application/json
 *    parameters:
 *    - in: body
 *      name: agentCode
 *      required: true
 *      schema:
 *        type: string
 *        $ref: "#/definitions/agentPatch"
 *    requestBody:
 *      request: true
 *      content:
 *        application/json:
 *          schema:
 *            $ref: "#definitions/agentPatch"
 *    responses:
 *      200:
 *       description: A successfull response from agents
 * definitions:
 *   agentPatch:
 *     type: object
 *     required:
 *     - agentCode
 *     - agentName
 *     - workingArea
 *     - commission
 *     - phoneNo
 *     - country
 *     properties:
 *       agentCode:
 *         type: string
 *         example: A300
 *       agentName:
 *         type: string
 *         example: PallaviBhadri
 *       workingArea:
 *         type: string
 *         example: Pune
 *       commission:
 *         type: number
 *         example: 5
 *       phoneNo:
 *         type: string
 *         example: 4147377529
 *       country:
 *         type: string
 *         example: India
*/
app.patch('/agents',(request,response) =>{
    pool.query(`update sample.agents set agent_name = '${request['body'].agentName}',  working_area = '${request['body'].workingArea}', commission  = '${request['body'].commission}', phone_no = '${request['body'].phoneNo}', country = '${request['body'].country}' where agent_code = '${request['body'].agentCode}'`).then(res => {
                console.log(res.affectedRows);
                if(res.affectedRows > 0)
                {
                        response.statusCode = 200;
                        response.setHeader('Content-Type','Application/json');
                        response.send(res);
                }
                else{
                    pool.query(`insert into sample.agents values('${request['body'].agentCode}', '${request['body'].agentName}', '${request['body'].workingArea}', '${request['body'].commission}', '${request['body'].phoneNo}', '${request['body'].country}')`).then(res1 => {
                        if(res1.affectedRows > 0)
                        {
                            response.statusCode = 200;                 
                            response.setHeader('Content-Type','Application/json');
                            response.send(res1);
                        }
                        else{
                            response.statusCode = 201;
                            response.setHeader('Content-Type','text/plain');
                            response.send("The agent is not located in the table - Operation  unsuccessful");
                        }
                    })
                    .catch(err =>{
                        response.statusCode = 500;
                        console.error('Error executing query', err.stack);
                        response.setHeader('Content-Type','text/plain');
                        response.send('Error executing query' + err.stack);
                    });
                }
              })
        .catch(err =>{
                response.statusCode = 404;
                console.error('Error executing query', err.stack);
                response.setHeader('Content-Type','text/plain');
                response.send('Error executing query' + err.stack);
        });
});



});